coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "test/**/*"
  - "build-*/**/*"
  - "etc/**/*"
  - "bin/**/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
