name: Build AppImage Intel RealSense

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'

on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: string
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  appimage:
    name: AppImage Build Intel RealSense
    runs-on: [buildjet-2vcpu-ubuntu-2204-arm]
    container:
      image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
      options: --platform linux/arm64
    timeout-minutes: 30

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: make package

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Upload Files
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        headers: "Cache-Control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false
