name: Build AppImage Intel RealSense

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'amd64-build'
    paths-ignore:
      - 'README.md'

jobs:
  appimage:
    name: AppImage Build Intel RealSense
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - os: 'buildjet-8vcpu-ubuntu-2204-arm'
            container:
              image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
              options: '--platform linux/arm64'
            cmd: 'make appimage-arm64'
          - os: 'ubuntu-latest'
            container:
              image: ghcr.io/viamrobotics/viam-camera-realsense:amd64
              options: '--platform linux/amd64'
            cmd: 'make appimage-amd64'

    container: ${{ matrix.container }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: ${{ matrix.cmd }}

      - name: Authorize GCP Upload
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Upload Files
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          headers: "cache-control: no-cache"
          path: 'packaging/appimages/deploy/'
          destination: 'packages.viam.com/apps/camera-servers/'
          glob: '*'
          parent: false
          gzip: false
