name: Build AppImage Intel RealSense

on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: string
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  appimage:
    name: AppImage Build Intel RealSense
    strategy:
      matrix:
        include:
          - arch: [arm64, qemu-host]
            image: ghcr.io/viamrobotics/viam-camera-realsense:arm64-cache
            platform: linux/arm64
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 30

    steps:
    - name: Check out code
      if: inputs.release_type != 'pr'
      uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Check out PR branch code
      if: inputs.release_type == 'pr'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: recursive

    - name: apt update
      run: |
        sudo apt update

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Build and Package (PR)
      if: inputs.release_type == 'pr'
      run: |
        make package

    - name: Build and Package (Latest)
      if: inputs.release_type == 'latest'
      run: |
        make package

    - name: Deploy Files
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        headers: "cache-control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false
