name: Build AppImage Intel RealSense

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'amd64-build' ]
    paths-ignore:
      - 'README.md'

jobs:
  appimage:
    name: AppImage amd64 Build Intel RealSense
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
      options: --platform linux/arm64
    timeout-minutes: 30

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: make appimage-amd64

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Upload Files
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        headers: "cache-control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false
