name: Publish Docker
on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: string
  workflow_call:
    inputs:
      release_type:
        required: true
        type: string
      secrets:
        GITHUB_TOKEN:
          required: true

jobs:
  docker:
    name: Build Docker Image
    strategy:
      matrix:
        include:
          - arch: [buildjet-2vcpu-ubuntu-2204-arm]
            image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
            platform: linux/arm64
            make_target: 'docker-cache-arm64-ci'
    runs-on: ${{ matrix.arch }}
    container:
      image: ${{ matrix.image }}
      options: --platform ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build and Push
      run: |
        make ${{ matrix.make_target}}
