name: Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'amd64-build'
      - 'main'
    paths:
      - 'etc/Dockerfile.debian.bookworm'

jobs:
  docker:
    name: Build Docker Image
    permissions:
      packages: write
    timeout-minutes: 45
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - buildjet-16vcpu-ubuntu-2204-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and Push
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            make docker-amd64-ci
          elif [ "${{ matrix.os }}" = "buildjet-16vcpu-ubuntu-2204-arm" ]; then
            make docker-arm64-ci
          fi