name: Publish Docker

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths: ['etc/**']

jobs:
  docker:
    name: Build Docker Image
    runs-on: [buildjet-2vcpu-ubuntu-2204-arm]
    container:
      image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
      options: --platform linux/arm64
            make_target: 'docker-arm64-ci'
    timeout-minutes: 30

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build and Push
      run: make docker-arm64-ci
