name: Build Integration Tests AppImage

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'amd64-build' ]
    paths:
      - 'integration/**'

jobs:
  appimage:
    name: Integration Tests for RealSense
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: buildjet-8vcpu-ubuntu-2204-arm
            container:
              image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
              options: --platform linux/arm64
            cmd: make integration-appimage-arm64
            arch: arm64
          - os: ubuntu-latest
            container:
              image: ghcr.io/viamrobotics/viam-camera-realsense:amd64
              options: --platform linux/amd64
            cmd: make integration-appimage-amd64
            arch: amd64

    container: ${{ matrix.container }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Integration Tests
      run: ${{ matrix.cmd }}

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Upload Files
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        headers: "cache-control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false
