name: Build module.tar.gz and upload artifact

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
        description: realsense module branch to run on

jobs:
  module:
    name: Intel RealSense module.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            container:
              image: ubuntu:22.04
            artifact-name: module-arm64
            profile-name: arm64-profile
          - os: ubuntu-22.04
            container:
              image: ubuntu:22.04
            artifact-name: module-amd64
            profile-name: amd64-profile

    container: ${{ matrix.container }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Restore cached libraries
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ matrix.os }}-conan-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ matrix.os }}-conan-

      - name: Install dependencies
        run: |
          cat /etc/*-release
          ldd --version
          uname -a

          apt-get update
          apt-get -y dist-upgrade
          DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
              autoconf \
              automake \
              build-essential \
              ca-certificates \
              curl \
              doxygen \
              g++ \
              git \
              gdb \
              gnupg \
              gpg \
              less \
              libssl-dev \
              libudev-dev \
              ninja-build \
              pkg-config \
              python3 \
              python3-pip \
              software-properties-common \
              sudo \
              wget \

          sudo wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          sudo echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null

          apt-get update
          apt-get -y install cmake=3.25.2-0kitware1ubuntu22.04.1 cmake-data=3.25.2-0kitware1ubuntu22.04.1


      - name: Setup python and conan
        run: |
          pip install conan
          cp etc/conan/${{ matrix.profile-name }} ~/.conan2/profiles/default
          conan profile show

      - name: Get librealsense
        run: |
          git clone https://github.com/lia-viam/conan-center-index.git
          cd conan-center-index
          git checkout realsense-2.55.1
          conan create recipes/librealsense/all/conanfile.py --version=2.56.5 --build=missing

      - name: Get Viam SDK
        run: |
          git clone https://github.com/viamrobotics/viam-cpp-sdk.git
          cd viam-cpp-sdk
          git checkout releases/v0.19.0
          conan create . -o "&:shared=False" --build=missing -s compiler.cppstd=17

      - name: Build
        run: |
          conan create . --build=missing -o "viam-cpp-sdk/*:shared=False"
          conan install --requires=viam-camera-realsense/0.0.1 --deployer-package "&" -o "viam-cpp-sdk/*:shared=False" -v v

      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: module.tar.gz
